--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NoobyPE/CitizenLibrary
build-by-default: true
branches:
- master
projects:
  CitizenLibrary:
    path: ""
    model: virion
    type: library
...
